name: islami
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  provider: ^6.1.2
  easy_localization: ^3.0.7
  flutter_native_splash: ^2.4.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true

  image_path: "assets/images/logo2.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo2.png"

flutter_native_splash:
  image: assets/images/logo2.png
  color: "#ffffff"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo2.png
    - assets/images/3.0x/head_sebha_logo@3x.png
    - assets/images/3.0x/body_sebha_dark@3x.png
    - assets/images/
    - assets/files/
    - assets/translation/
